### ISSUE TITLE
Dataset download problems

### ISSUE THREAD

**Issue by yuxijin** [gaow0007/Fast-Multi-Video-Style-Transfer#1]
Hi, when I was trying to download the content dataset from the first link you have provided, it said that 
"Resolving vllab1.ucmerced.edu (vllab1.ucmerced.edu)... 169.236.184.68
Connecting to vllab1.ucmerced.edu (vllab1.ucmerced.edu)|169.236.184.68|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-12-27 21:58:06 ERROR 403: Forbidden."
Can you help me to finish these issues?

**Comment by ChauvinisticJonatha** [comment]
> Hi, when I was trying to download the content dataset from the first link you have provided, it said that
> "Resolving vllab1.ucmerced.edu (vllab1.ucmerced.edu)... 169.236.184.68
> Connecting to vllab1.ucmerced.edu (vllab1.ucmerced.edu)|169.236.184.68|:80... connected.
> HTTP request sent, awaiting response... 403 Forbidden
> 2020-12-27 21:58:06 ERROR 403: Forbidden."
> Can you help me to finish these issues?

I meet with the same question. Have you sloved it? I am trying to contact with author.

**Comment by gaow0007** [comment]
Sorry, I have no access right towards vllab1.ucmerced.edu related website.  You can reach https://www.wslai.net/ to ask him the dataset.
